# Generated by Django 4.2.27 on 2026-01-28 23:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='선박명')),
                ('imo_number', models.CharField(max_length=20, unique=True, verbose_name='IMO 번호')),
                ('vessel_type', models.CharField(max_length=50, verbose_name='선박 유형')),
                ('flag', models.CharField(max_length=50, verbose_name='선적국')),
                ('built_year', models.IntegerField(verbose_name='건조년도')),
                ('gross_tonnage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='총톤수')),
                ('current_location', models.CharField(blank=True, max_length=200, verbose_name='현재 위치')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='최종 업데이트')),
                ('vms_version', models.CharField(default='1.0.0', max_length=20, verbose_name='VMS 버전')),
                ('is_online', models.BooleanField(default=False, verbose_name='온라인 상태')),
            ],
            options={
                'verbose_name': '선박',
                'verbose_name_plural': '선박 목록',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='배포 버전')),
                ('deployed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='배포 시각')),
                ('status', models.CharField(choices=[('success', '성공'), ('failed', '실패'), ('rollback', '롤백')], max_length=20, verbose_name='상태')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='소요 시간(초)')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='vessel.vessel')),
            ],
            options={
                'verbose_name': '배포 이력',
                'verbose_name_plural': '배포 이력',
                'ordering': ['-deployed_at'],
            },
        ),
    ]
